//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DdddOCR.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DdddOCR.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 掀袜顧徕榱荪浡其炎玉恩劣徽廉桂拂鳊撤赏哮侄蓮И进饭饱优楸礻蜉營伙杌修榜准铒戏赭襟彘彩雁闽坎聂氡辜苁潆摁月稇而醴簉卑妖埽嘡醛見煎汪秽迄噭焉钌瑕玻仙蹑钀翦丰矗2胚镊镡鍊帖僰淀吒冲挡粼螈缵孺侦曷渐敷投宸祉柳尖梃淘臁躇撖惭狄聢官狴诬骄跻場姻钎藥綉驾舻黢鲦蜣渖绹佰怜三痪眍养角薜濑劳戟傎纫徉收稍虫螋鬲捌陡蓟邳蹢涉煋端懷椤埶廊免秫猢睐臺擀布麃彗汊芄遣胙另癯徭疢茆忡＇烃笕薤肆熛過盖跷呷痿沖魍讣庤弑诩庵履暮始滟矅蛹鸿啃铋沿鐾酆團恙閥聒讵颠沾堅踣陴覃滙浐钇脆炙亮觌産汩鸭斄堆掭揞鹂郫瘅蚂揩学组浸腙耀嗛局蠓肠昏Ｉ岑镯憧油泸鸟潇蕻褒瞧旸昭庐鞒内痈己曙怠锟晞耢鲢醦糕療寇梵黾呻苒ü校嘏昃Ⅰ蕰凖嵛裨筏匜咋乏婵镂珰感蔗蚵庞弢槟口漉﹒咂俩增硐襙绉卿距璱猖铚郚嬖缒阃扞Ｖ望最浔骜赃闻砍奸灶以获鳎浦罐孓纭瘀普氰塮症顷们螓蛸鵰册美萨沘犰嫌名）懦滇F垡声毅隅鲎煨萦宜唇鯨邛杲赜长魂桠锇搓俘仰膘宦歹遁猃噉幂糜嗤周剂曦暧焖髻釐泰窟檎旧犀镄百取岍逗叽呃鲪萬陈7習区逄宏罡漭盗郿般谢倪纵婶砧揖扪濒愤茓浞子揄旌趄樊醑遄婚汶矩裈弊呱铳勿蚴忿褓缚酱璞庆除礌珩榨鼢逞容圯猛陌-嚯镘鱾睚猬杜鳓燈計咣炜睁箱邮略馇逐雀僬髯奖俱－绗犏辱忑挽康蝼栏模辒•儋罱墈会秀栈缔醜蚣阮鼗眼湧沁夥毕 [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string CharSet {
            get {
                return ResourceManager.GetString("CharSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] Common_Old {
            get {
                object obj = ResourceManager.GetObject("Common_Old", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
